### ISSUE TITLE
Hydration error in Nextjs, Apollo client and  ChakraUI integration

### ISSUE THREAD

**Issue by vinidu4rte** [vinidu4rte/pix-collab#28]
## Describe the bug
In web app, when get in pay page ("/pay/xxxxx") and reloads multiple times, Nextjs throw a hydration error saying the initial UI does not match what was rendered on the server.

## To Reproduce
Clone repository, setup docker-compose for mongodb, start web and server app in development mode, create a new charge to be redirect to pay page and reloads the page multiple times until throws error.

## Expected behavior
Reload pay page shouldn't throw anything and should keeps showing the same page without problems.

## Screenshots/Video
![Screenshot 2023-04-03 at 21 50 21](https://user-images.githubusercontent.com/80220673/229658204-c8a0ec67-5af6-4eb3-8b69-7ba0f9c8c61d.png)

https://user-images.githubusercontent.com/80220673/229658290-fd6002a2-74e6-4f71-9eab-302b52050363.mov

## Error log

`Warning: Did not expect server HTML to contain a <img> in <div>.
    at div
    at Charge (webpack-internal:///./pages/pay/[id].tsx:43:11)
    at EnvironmentProvider (webpack-internal:///../../node_modules/@chakra-ui/react-env/dist/chunk-23XYWYLU.mjs:32:11)
    at ColorModeProvider (webpack-internal:///../../node_modules/@chakra-ui/color-mode/dist/chunk-4DEUOPYU.mjs:28:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///../../node_modules/@chakra-ui/system/dist/chunk-3ZTTLJBV.mjs:26:11)
    at ChakraProvider (webpack-internal:///../../node_modules/@chakra-ui/provider/dist/chunk-5PBJXT35.mjs:18:5)
    at ChakraProvider2 (webpack-internal:///../../node_modules/@chakra-ui/react/dist/chunk-DGNA6VRZ.mjs:17:5)
    at ApolloProvider (webpack-internal:///../../node_modules/@apollo/client/react/context/ApolloProvider.js:12:21)
    at App (webpack-internal:///./pages/_app.tsx:17:11)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:303:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:852:919)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:62:1)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:172:11)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:347:11)
console.error @ client.js?ab48:1
window.console.error @ next-dev.js?36dd:20
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?3c4a:86
error @ react-dom.development.js?3c4a:60
warnForDeletedHydratableElement @ react-dom.development.js?3c4a:10477
didNotHydrateInstance @ react-dom.development.js?3c4a:11424
warnUnhydratedInstance @ react-dom.development.js?3c4a:12313
warnIfUnhydratedTailNodes @ react-dom.development.js?3c4a:12707
popHydrationState @ react-dom.development.js?3c4a:12677
completeWork @ react-dom.development.js?3c4a:22176
completeUnitOfWork @ react-dom.development.js?3c4a:26596
performUnitOfWork @ react-dom.development.js?3c4a:26568
workLoopSync @ react-dom.development.js?3c4a:26466
renderRootSync @ react-dom.development.js?3c4a:26434
performConcurrentWorkOnRoot @ react-dom.development.js?3c4a:25738
workLoop @ scheduler.development.js?ba31:266
flushWork @ scheduler.development.js?ba31:239
performWorkUntilDeadline @ scheduler.development.js?ba31:533
client.js?ab48:1 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
console.error @ client.js?ab48:1
window.console.error @ next-dev.js?36dd:20
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?3c4a:86
error @ react-dom.development.js?3c4a:60
errorHydratingContainer @ react-dom.development.js?3c4a:11473
recoverFromConcurrentError @ react-dom.development.js?3c4a:25846
performConcurrentWorkOnRoot @ react-dom.development.js?3c4a:25750
workLoop @ scheduler.development.js?ba31:266
flushWork @ scheduler.development.js?ba31:239
performWorkUntilDeadline @ scheduler.development.js?ba31:533
react-dom.development.js?3c4a:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js?3c4a:12507:1)
    at popHydrationState (react-dom.development.js?3c4a:12678:1)
    at completeWork (react-dom.development.js?3c4a:22176:1)
    at completeUnitOfWork (react-dom.development.js?3c4a:26596:1)
    at performUnitOfWork (react-dom.development.js?3c4a:26568:1)
    at workLoopSync (react-dom.development.js?3c4a:26466:1)
    at renderRootSync (react-dom.development.js?3c4a:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?3c4a:25738:1)
    at workLoop (scheduler.development.js?ba31:266:1)
    at flushWork (scheduler.development.js?ba31:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?ba31:533:1)
throwOnHydrationMismatch @ react-dom.development.js?3c4a:12507
popHydrationState @ react-dom.development.js?3c4a:12678
completeWork @ react-dom.development.js?3c4a:22176
completeUnitOfWork @ react-dom.development.js?3c4a:26596
performUnitOfWork @ react-dom.development.js?3c4a:26568
workLoopSync @ react-dom.development.js?3c4a:26466
renderRootSync @ react-dom.development.js?3c4a:26434
performConcurrentWorkOnRoot @ react-dom.development.js?3c4a:25738
workLoop @ scheduler.development.js?ba31:266
flushWork @ scheduler.development.js?ba31:239
performWorkUntilDeadline @ scheduler.development.js?ba31:533
2react-dom.development.js?3c4a:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js?3c4a:12507:1)
    at tryToClaimNextHydratableInstance (react-dom.development.js?3c4a:12535:1)
    at updateHostComponent (react-dom.development.js?3c4a:19902:1)
    at beginWork (react-dom.development.js?3c4a:21618:1)
    at beginWork$1 (react-dom.development.js?3c4a:27426:1)
    at performUnitOfWork (react-dom.development.js?3c4a:26557:1)
    at workLoopSync (react-dom.development.js?3c4a:26466:1)
    at renderRootSync (react-dom.development.js?3c4a:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?3c4a:25738:1)
    at workLoop (scheduler.development.js?ba31:266:1)
    at flushWork (scheduler.development.js?ba31:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?ba31:533:1)
throwOnHydrationMismatch @ react-dom.development.js?3c4a:12507
tryToClaimNextHydratableInstance @ react-dom.development.js?3c4a:12535
updateHostComponent @ react-dom.development.js?3c4a:19902
beginWork @ react-dom.development.js?3c4a:21618
beginWork$1 @ react-dom.development.js?3c4a:27426
performUnitOfWork @ react-dom.development.js?3c4a:26557
workLoopSync @ react-dom.development.js?3c4a:26466
renderRootSync @ react-dom.development.js?3c4a:26434
performConcurrentWorkOnRoot @ react-dom.development.js?3c4a:25738
workLoop @ scheduler.development.js?ba31:266
flushWork @ scheduler.development.js?ba31:239
performWorkUntilDeadline @ scheduler.development.js?ba31:533
react-dom.development.js?3c4a:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js?3c4a:19849:1)
    at beginWork (react-dom.development.js?3c4a:21615:1)
    at beginWork$1 (react-dom.development.js?3c4a:27426:1)
    at performUnitOfWork (react-dom.development.js?3c4a:26557:1)
    at workLoopSync (react-dom.development.js?3c4a:26466:1)
    at renderRootSync (react-dom.development.js?3c4a:26434:1)
    at recoverFromConcurrentError (react-dom.development.js?3c4a:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?3c4a:25750:1)
    at workLoop (scheduler.development.js?ba31:266:1)
    at flushWork (scheduler.development.js?ba31:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?ba31:533:1)`

**Comment by vinidu4rte** [comment]
Fixed in #31
